routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 		'Site\SiteController@landing'					)->name('landing');
Route::get('/maestros', 'Site\SiteController@maestros'					)->name('maestros');
Route::get('/clases', 	'Site\SiteController@clases'					)->name('clases');
Route::get('/eventos', 	'Site\SiteController@eventos'					)->name('eventos');
Route::get('/galeria/{photo_page?}', 	'Site\SiteController@galeria'					)->name('galeria');
Route::get('/galeria/detalle/{slug}', 	'Site\SiteController@galeriaDetalle'					)->name('galeria.detalle');
Route::get('/horarios', 'Site\HorariosController@index'					)->name('horarios');
Route::get('/contacto', 'Site\SiteController@contacto'					)->name('contacto');
Route::post('/contacto', 'Site\SiteController@contacto_email'			)->name('contacto_email');
Route::get('/descarga-horario', 'Site\SiteController@descargaPdf'			)->name('descargaPdf');

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
	
	Route::prefix('clases')->name('clases.')->group(function () {
		Route::get('/', 'ClasesController@index')->name('index');
		Route::get('/editar/{id?}', 'ClasesController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'ClasesController@save')->name('save');
		Route::delete('/delete', 'ClasesController@delete')->name('delete');
	});
	
	Route::prefix('maestros')->name('maestros.')->group(function () {
		Route::get('/', 'MaestrosController@index')->name('index');
		Route::get('/editar/{id?}', 'MaestrosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'MaestrosController@save')->name('save');
		Route::delete('/delete', 'MaestrosController@delete')->name('delete');
	});
	
	Route::prefix('horarios')->name('horarios.')->group(function () {
		Route::get('/', 'HorariosController@index')->name('index');
		Route::get('/editar/{id?}', 'HorariosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'HorariosController@save')->name('save');
		Route::delete('/delete', 'HorariosController@delete')->name('delete');
	});
	
	Route::prefix('eventos')->name('eventos.')->group(function () {
		Route::get('/', 'EventosController@index')->name('index');
		Route::get('/editar/{id?}', 'EventosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'EventosController@save')->name('save');
		Route::delete('/delete', 'EventosController@delete')->name('delete');
	});
	
});

/*Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});*/

Route::get('/pass', function () {
    dd(bcrypt('stepup'));
});

app/Http/Controllers/Admin/ClasesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Clase;

use App\Http\Requests\Admin\ClasesRequest; 

use App\Traits\DecryptValues;

use DB;
use Storage;

class ClasesController extends Controller
{
	use DecryptValues;
	
    public function index(){
	    $clases = Clase::orderBy('nombre','asc')->paginate(50);
	    
	    return view('admin.clases.index')->with(compact('clases'));
    }
    
    public function edit(Request $request){
	    $id = $request->id;
	    $clase = null;
	    if(!empty($id)){
			$id = $this->decryptValue($id);
			
			if(!$id){
				return back()->withErrors('El registro seleccionado no es válido');
			} 
			
			$clase = Clase::where('id', $id)->first();  
	    }
	    
	    return view('admin.clases.edit')->with(compact('clase'));
    }
    
    public function save(ClasesRequest $request){
	    $id = $request->id;
	    DB::beginTransaction();
	    
	    $clase = new Clase;
	    if(!empty($id)){
			$id = $this->decryptValue($id);
			
			if(!$id){
				DB::rollBack();
				return back()->withErrors('El registro seleccionado no es válido');
			}
			
			$clase = Clase::where('id', $id)->first();
			if(!$clase){
				DB::rollBack();
				return back()->withErrors('El registro seleccionado no es válido');
			}   
	    }
	    
	    $nombre = $request->nombre;
	    $detalle = $request->detalle;
	    $descripcion = $request->descripcion;
	    
	    $clase->nombre = $nombre;
	    $clase->detalle = $detalle;
	    $clase->descripcion = $descripcion;
	    $clase->save();
	    
	    if($request->hasFile('foto')){
		    if($clase->foto){
				if(Storage::disk('clases')->exists($clase->foto)){
				    Storage::disk('clases')->delete($clase->foto);
			    }
			}
		    
		    $nombre_imagen = 'CLASE-'.$clase->id.time().'.'.$request->file('foto')->extension();
	    
		    $request->foto->storeAs('', $nombre_imagen, 'clases');
		    
		    $clase->foto = $nombre_imagen;
		    
		    $clase->save();
	    }
	    
	    DB::commit();
	    
	    return redirect()->route('admin.clases.edit', ['id' => encrypt($clase->id)])->with('mensaje', 'El registró se guardó correctamente');
    }
    
    public function delete(Request $request){
	    $id = $request->id;
	    
	    if(empty($id)){
		    return response()->json('El registro seleccionado no es válido', 400);
	    }
	    
	    $id = $this->decryptValue($id);
	    if(!$id){
		    return response()->json('El registro seleccionado no es válido', 400);
	    }
	    
	    $clase = Clase::find($id);
	    
	    if(!$clase){
		    return response()->json('No se encontró el registro seleccionado', 400);
	    }
	    
	    $clase->delete();
	    
	    return response()->json(array('estado' => 0, 'mensaje' => 'Se eliminó exitosamente'));
    }
    
}

resources/views/admin/clases/edit.blade.php
@extends('layouts.admin.template')

@section('titulo')
Clases
@endsection

@section('titulo_pagina')
Clases
@endsection

@section('active_clases')
active
@endsection

@section('content')
<div class="row">
	<div class="col-sm-12">
		<a href="{{ route('admin.clases.index') }}" class="btn btn-default"><i class="material-icons">chevron_left</i> Listado de Clases</a>
	</div>
</div>
<div class="card">
    <div class="card-header card-header-warning">
        <h3 class="card-title">Agregar/Editar Clase</h3>
        <p class="card-category">Formulario para clases</p>
    </div>
    <div class="card-body">
        <form method="post" action="{{ route('admin.clases.save') }}" enctype="multipart/form-data">
	        {{ csrf_field() }}
	        {{ $clase ? method_field('PUT') : '' }}
	        <input type="hidden" name="id" value="{{ $clase ? encrypt($clase->id) : '' }}">
	       
            <div class="row">
	            <div class="col-sm-6">
		            <div class="form-group">
					    <label for="nombre" class="bmd-label-floating">Nombre</label>
					    <input required="required" type="text" class="form-control" id="nombre" name="nombre" value="{{ old('nombre') ? old('nombre') : ($clase ? $clase->nombre : '') }}">
					</div>
	            </div>
	            <div class="col-sm-6">
		            <div class="form-group">
					    <label for="detalle" class="bmd-label-floating">Detalle</label>
					    <input  type="text" class="form-control" id="detalle" name="detalle" value="{{ old('detalle') ? old('detalle') : ($clase ? $clase->detalle : '') }}">
					</div>
	            </div>
            </div>
            <div class="row">
	            <div class="col-sm-6">
		            <div class="form-group">
			            <label for="descripcion">Descripción.</label>
					    <textarea id="descripcion" name="descripcion"></textarea>
		            </div>
	            </div>
            
		        <div class="col-sm-6 text-center">
				    <div class="form-group">
					    <label>Foto*</label>
					    <div class="preview-container">
                        	<div class="preview-img" id="preview" style="background-image: url('{{ $clase ? asset("public/storage/clases/".$clase->foto) : asset("public/images/admin/misc/img-placeholder.png") }}')">
						    
					    	</div>
					    </div>
					    <div>
					    	<small>(Tamaño recomendado 1500x700. La imagen no puede pesar más de 5 MB)</small>
				    	</div>
					    <label style="color: white;" for="foto" class="btn btn-warning">Clic aquí para cambiar la imagen</label>
					    <input accept=".png, .jpg, .jpeg" type="file" class="form-control imagenes" name="foto" id="foto" value="{{ old('foto') ? old('foto') : '' }}">
				    </div>
			    </div>
	        </div>
            
            <div class="row">
	            <div class="col-sm-12 text-right">
		            <button type="submit" href="{{ route('admin.clases.index') }}" class="btn btn-warning"><i class="material-icons">check</i> Guardar</a>
	            </div>
            </div>
        </form>
    </div>
</div>
@endsection


@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<style>
	.preview-container{
		width: 150px;
		height: 150px;
		margin: 0 auto;
	}
	
	.preview-img{
		width: 150px;
		height: 150px;
		background-position: center center;
		background-size: 100% auto;
		background-repeat: no-repeat;
		border-radius: 50%;
	}
	
	.fancybox-preview{
		text-align: center;
	}
	
	.imagenes{
		display: none;
	}
	
	.container-template{
		margin-bottom: 50px;
	}
	
	.note-toolbar-wrapper{
		background-color: #f5f5f5;
	}
	
	input.note-image-input.note-form-control.note-input{
		z-index: 100;
		opacity: 1;
		position: relative;
	}
	.note-editor.note-frame .note-editing-area .note-editable{
		min-height: 300px;
	}
</style>

@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/lang/summernote-es-ES.js"></script>
<script>
	$(document).ready(function() {
	    clasesSelect();
	    iniciarImg();
		comprobarImg();
		iniciarSummernote();
	});
	
	function clasesSelect(){
		$('#clases').select2({
			placeholder: ''
		});
	}
	
	function hasExtension(inputID, exts){
		var fileName = document.getElementById(inputID).value;
		return (new RegExp('(' + exts.join('|').replace(/\./g, '\\.') + ')$', "i")).test(fileName);
	}
	
	function readURL(input) {
		var id = $(input).attr('id');
		if(input.files && input.files[0]) {
			var reader = new FileReader();
			
			if(hasExtension(id, ['.jpg', '.png', 'jpeg'])){
				reader.onload = function(e) {
			    	$('#preview').css('background-image', 'url(' + e.target.result + ')');
			    }
				reader.readAsDataURL(input.files[0]);
			}else{
				alertError('El formato de la imagen no es un formato válido');
			}
		}
	}
	
	function iniciarImg(){
		$(document).on('change', '.imagenes', function() {
			readURL(this);
		});
	}
	
	function comprobarImg(){
		if($('.imagenes').length > 0){
			$('.imagenes').each(function(i, elem){
				if ($(elem).get(0).files.length > 0) {
					readURL(elem);
				}
			});
		}
		
	}
	function iniciarSummernote(){
		$('#descripcion').summernote({
			lang: 'es-ES'
		});
		
		$('.btn-primary').removeClass('btn-primary').addClass('btn-warning');
		$('#descripcion').summernote('code', $('#summernoteMark').html());
	}
</script>
@endsection

resources/views/admin/clases/index.blade.php
@extends('layouts.admin.template')

@section('titulo')
Clases
@endsection

@section('titulo_pagina')
Clases
@endsection

@section('active_clases')
active
@endsection

@section('content')
<div class="card">
    <div class="card-header card-header-warning">
        <h4 class="card-title mt-0"> Lista de Clases</h4>
        <p class="card-category"> Clases registradas en el sistema</p>
    </div>
    <div class="card-body">
	    <div class="row">
		    <div class="col-sm-12 text-right">
			    <a href="{{ route('admin.clases.edit') }}" class="btn btn-default"><i class="material-icons">add</i> Agregar Nueva Clase</a>
		    </div>
	    </div>
	    @if($clases->isNotEmpty())
	    <div class="row">
		    <div class="col-sm-12">
		        <div class="table-responsive">
		            <table class="table table-hover">
		                <thead class="">
		                    <tr>
		                        <th>
		                            Nombre
		                        </th>
		                        <th>
		                            Detalle
		                        </th>
		                        <th>
		                            Acciones
		                        </th>
		                    </tr>
		                </thead>
		                <tbody>
		                    @foreach($clases as $clase)
		                    <tr>
			                    <td>
				                    <b>{{ $clase->nombre }}</b> 
			                    </td>
			                    <td>
				                    {{ $clase->detalle }}
			                    </td>
			                    <td>
				                    <a href="{{ route('admin.clases.edit', ['id' => encrypt($clase->id)]) }}" class="btn btn-warning btn-round btn-fab">
						            	<i class="material-icons">edit</i>
										<div class="ripple-container"></div>
						            </a>
						            <button type="button" class="btn btn-danger btn-round btn-fab eliminar" data-id="{{ encrypt($clase->id) }}">
						            	<i class="material-icons">delete</i>
										<div class="ripple-container"></div>
						            </button>
			                    </td>
		                    </tr>
		                    @endforeach
		                </tbody>
		            </table>
		        </div>
		    </div>
	    </div>
	    <div class="row">
		    <div class="col-sm-12">
			    <div class="paginacion text-center">
			    	{{ $clases->links() }}
			    </div>
		    </div>
	    </div>
        @else
        <h5>No hay registros todavía...</h5>
        @endif
    </div>
</div>
@endsection

@section('js')
	<script type="text/javascript">
		var rutaEliminar = "{{ route('admin.clases.delete') }}";
		
		function eliminar(id){
			$.ajax({
				headers: {
			        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			    },
		    	type: 'POST',
				url: rutaEliminar,
				data: {id:  id, _method: 'delete' },
				dataType: 'json',
				beforeSend: function(){
			    }
			}).done(function(response) {
				var estado = response.estado;
				if(estado == 0){
					alertSuccess(response.mensaje, true);
				}
				if(estado == 1){
					alertError(response.mensaje);
				}
		    }).fail(function(data) {
			    var errors = data.responseJSON;
			    var html = '';
			    if(errors instanceof Array){
				    $.each( errors, function( key, value ) {
						for(var i = 0; i < value.length; i++){
							html += '<li>'+ value[i] +'</li>';
						}
		            });
			    }else{
				    html = data.responseJSON;
			    }
			    alertError(html);
		    });
		}
	</script>
@endsection