routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 		'Site\SiteController@landing'					)->name('landing');
Route::get('/maestros', 'Site\SiteController@maestros'					)->name('maestros');
Route::get('/clases', 	'Site\SiteController@clases'					)->name('clases');
Route::get('/eventos', 	'Site\SiteController@eventos'					)->name('eventos');
Route::get('/galeria/{photo_page?}', 	'Site\SiteController@galeria'					)->name('galeria');
Route::get('/galeria/detalle/{slug}', 	'Site\SiteController@galeriaDetalle'					)->name('galeria.detalle');
Route::get('/horarios', 'Site\HorariosController@index'					)->name('horarios');
Route::get('/contacto', 'Site\SiteController@contacto'					)->name('contacto');
Route::post('/contacto', 'Site\SiteController@contacto_email'			)->name('contacto_email');
Route::get('/descarga-horario', 'Site\SiteController@descargaPdf'			)->name('descargaPdf');

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('auth')->group(function () {
	
	Route::prefix('clases')->name('clases.')->group(function () {
		Route::get('/', 'ClasesController@index')->name('index');
		Route::get('/editar/{id?}', 'ClasesController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'ClasesController@save')->name('save');
		Route::delete('/delete', 'ClasesController@delete')->name('delete');
	});
	
	Route::prefix('maestros')->name('maestros.')->group(function () {
		Route::get('/', 'MaestrosController@index')->name('index');
		Route::get('/editar/{id?}', 'MaestrosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'MaestrosController@save')->name('save');
		Route::delete('/delete', 'MaestrosController@delete')->name('delete');
	});
	
	Route::prefix('horarios')->name('horarios.')->group(function () {
		Route::get('/', 'HorariosController@index')->name('index');
		Route::get('/editar/{id?}', 'HorariosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'HorariosController@save')->name('save');
		Route::delete('/delete', 'HorariosController@delete')->name('delete');
	});
	
	Route::prefix('eventos')->name('eventos.')->group(function () {
		Route::get('/', 'EventosController@index')->name('index');
		Route::get('/editar/{id?}', 'EventosController@edit')->name('edit');
		Route::match(['post', 'put'], '/save', 'EventosController@save')->name('save');
		Route::delete('/delete', 'EventosController@delete')->name('delete');
	});
	
});

/*Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});*/

Route::get('/pass', function () {
    dd(bcrypt('stepup'));
});

resources/views/layouts/admin/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="#">@yield('titulo_pagina')</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                <form class="navbar-form" method="post" action="{{ route('logout') }}">
	                {{ csrf_field() }}
                    <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <i class="material-icons">arrow_drop_down</i>
                        <!--span class="notification">5</span-->
                        <p class="d-lg-none d-md-block">
                            Acciones
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <button class="dropdown-item" type="submit">Cerrar Sesión</button>
                    </div>
                </form>
                </li>
            </ul>
           
        </div>
    </div>
</nav>

resources/views/layouts/admin/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="black" data-image="https://demos.creative-tim.com/material-dashboard/assets/img/sidebar-3.jpg">
    <!--
Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

Tip 2: you can also add an image using data-image tag
-->
    <div class="logo">
        <a href="#" class="simple-text logo-normal">
			<img src="{{ asset('images/logo-transparente.png') }}" class="img-responsive" style="width: 150px;">
		</a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            {{-- <li class="nav-item  ">
                <a class="nav-link" href="./dashboard.html">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li> --}}
            <li class="nav-item @yield('active_clases')">
                <a class="nav-link" href="{{ route('admin.clases.index') }}">
                    <i class="material-icons">person</i>
                    <p>Clases</p>
                </a>
            </li>
            <li class="nav-item @yield('active_maestros')">
                <a class="nav-link" href="{{ route('admin.maestros.index') }}">
                    <i class="material-icons">content_paste</i>
                    <p>Maestros</p>
                </a>
            </li>
            <li class="nav-item @yield('active_horarios')">
                <a class="nav-link" href="{{ route('admin.horarios.index') }}">
                    <i class="material-icons">library_books</i>
                    <p>Horario</p>
                </a>
            </li>
            <li class="nav-item @yield('active_eventos')">
                <a class="nav-link" href="{{ route('admin.eventos.index') }}">
                    <i class="material-icons">bubble_chart</i>
                    <p>Eventos</p>
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/layouts/admin/template.blade.php
<!doctype html>
<html lang="es">

	<head>
	    <title>Step Up Admin | @yield('titulo')</title>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
	
	    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	    
	    <!-- CSRF Token -->
		<meta name="csrf-token" content="{{ csrf_token() }}">
	
	    <!--     Fonts and icons     -->
	    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700" rel="stylesheet"> 
	    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Material+Icons" />
	    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	
	    <!-- Material Dashboard CSS -->
	    <link rel="stylesheet" href="{{ asset('css/admin/material-dashboard.css') }}">
	    
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
	    
	    <link rel="stylesheet" href="{{ asset('css/admin/custom.css') }}">
		
		@yield('css')
	</head>
	
	<body>
		@yield('modals')
	    <div class="wrapper ">
	        @include('layouts.admin.sidebar')
	        
	        <div class="main-panel">
	            @include('layouts.admin.navbar')
	            
	            <div class="content">
		            <div class="container-fluid">
	            	@yield('content')
		            </div>
	            </div>
	        </div>
	    </div>
	
	    <!--   Core JS Files   -->
	    <script src="{{ asset('js/admin/jquery.min.js') }}"></script>
	    <script src="{{ asset('js/admin/popper.min.js') }}"></script>
	    <script src="{{ asset('js/admin/bootstrap-material-design.min.js') }}"></script>
	    
		<!-- jQuery confirm -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
	
	    <!-- Material Dashboard Core initialisations of plugins and Bootstrap Material Design Library -->
	    <script src="{{ asset('js/admin/material-dashboard.min.js?v=2.1.0') }}"></script>
	    
	    <script src="{{ asset('js/admin/custom.js') }}" type="text/javascript"></script>
	    
	    @if($errors->any())
	    <script>
		    $(document).ready(function(){
				crearMensajeErrorPhp(); 
		    });
		    function crearMensajeErrorPhp(){
			    var htmlError = '';
				
				htmlError += 'Por favor, verifique los siguientes errores:<br><br><ul>';
			    @foreach ($errors->all() as $error)
			        htmlError += '<li>' + "{{ $error }}" + '</li>';
			    @endforeach
			    htmlError += '</ul>';
			    
			    alertErrorPhp(htmlError);
		    }
	    </script>
	    @endif
	    @if(session("mensaje"))
		<script>
			$(document).ready(function(){
				crearMensajeSuccessPhp(); 
		    });
			function crearMensajeSuccessPhp(){
				var mensaje = "{{ session('mensaje') }}";
				alertSuccessPhp(mensaje);
			}
		</script>
		@endif
	    
	    @yield('js')
	</body>

</html>